spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhuat/server-config
          search-paths:
          username:
          password:
      label: master

server:
  port: 1117
